<?php

namespace Database\Factories;

use App\Models\Category;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\SubCategory>
 */
class SubCategoryFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {

        return [
            'category_id' => Category::inRandomOrder()->first()->id,

            'name' =>[
                'ar' => $this->faker->randomElement([
                    'نزال مطبخ كف',
                    'نزال مطبخ', 'معلقة رفوف هرمية',
                    'معلقة رفوف',
                    'معلقة جيب ولادي',
                    'معلقة جيب بناتي',
                    'معلقة جيب',
                    'مطمورة',
                    "مشاية",
                    'مريول مطبخ',
                    'مريول حلاقة',
                    'مراية رف',
                    'مخدة رقبة',
                    'مجموعة مكياج',
                    'لوحة',
                    'لمبدير',
                    "لعبة",
                    'كيس معطر',
                    'كمامة',
                    'كرسي',
                    'قاعدة كاسة',
                    'قاعدة كاسات',
                    'قاعدة صحن',
                    'علاقة',
                    'صينية مراية',
                    'صندوق',
                    'صحن خشب',
                    'صبار',
                    'سيراميك',
                    'سلة ولادي',
                    'سلة منزلية',
                    'سلة غسيل',
                    'سلة بناتي',
                    'سلة أطفال',
                    'سلة',
                    'ساعة حائط',
                    'حقيبة مياه',
                    'حقيبة بحر',
                    'حقيبة احذية',
                    'جيب ملعقة',
                    'جرة',
                    'تابلو',
                    'cover eyes',
                    'مقلمة نسائية',
                    'مقلمة مدرسة',
                    'مقلمة',
                    'لفاحة',
                    'كمر نسائي',
                    'كمر',
                    'قوس شعر',
                    'قبعة',
                    'قبة',
                    'فولار',
                    'علاقة موبايل',
                    'علاقة مفاتيح',
                    'طوق نسائي',
                    'طوق + سوارة ولادي',
                    'طوق',
                    'شرشف',
                    'سوارة',
                    'سلسال نضارة',
                    'ساق وسط',
                    'ساق طويل رسمي',
                    'ساق طويل',
                    'ربطة شعر',
                    'دوكسايد مطاط',
                    'دوكسايد سليكون',
                    'دوكسايد',
                    'دبوس زينة',
                    'خلخال',
                    'خاتم',
                    'حلق',
                    'حقيبة يد',
                    'حقيبة نسائي على جنب',
                    'حقيبة نسائي',
                    'حقيبة موبايل',
                    'حقيبة مدرسة',
                    'حقيبة لاب توب',
                    'حقيبة كتف',
                    'حقيبة على جنب',
                    'حقيبة ظهر ولادي',
                    'حقيبة ظهر رجالي',
                    'حقيبة ظهر بناتي',
                    'حقيبة ظهر',
                    'حقيبة سيارة',
                    'حقيبة رياضة',
                    'حقيبة رجالي يد',
                    'حقيبة رجالي على جنب',
                    'حقيبة رجالي ظهر',
                    'حقيبة خصر نسائي',
                    'حقيبة خصر رجالي',
                    'حقيبة خصر',
                    'حقيبة بناتي',
                    'حقيبة ايباد',
                    'حقيبة',
                    'حبسة شعر',
                    'جزدان رجالي',
                    'جزدان',
                    'بند',
                    'الشين',
                    'اكسسوار',
                    "جراب",
                    "قميص",
                    'سالوبيت',
                    'بنطال',
                    "مايوه",
                    "طقم",
                    'شورت',
                    'دقونة',
                    'بيجاما',
                    'بلوز بولو',
                    'بلوز',
                    'بروتيل',
                    'بدي',
                    'افرول',
                    'فستان',
                    'بلوز مع فيزو',
                    'بربتوز',
                    'جاكيت',
                    'انوراك',
                    'بلوز ستريش',
                    'فيزو',
                    'تنورة',
                    'بنتكور',
                    'جامبر',
                    'سكليست',
                    'جيليه',
                    'بلوز قميص',
                    'قبة قميص',
                    'كاش مايو',
                    'كاب',
                    'شال',
                    'روب',
                    'جيله',
                    'بوليرو',
                    'بوستيه',
                    'بلوزة/بروتيل',
                    'بلوز حفر',
                    'مانطو',
                    'قميص حفر',
                    'روب نوم',
                    'فيزون',
                    'روب ديشامبر',
                    'وجه مخدة',
                    'مخدة ولادي',
                    'مخدة نوم',
                    'مخدة نجمة',
                    'مخدة مستطيلة',
                    'مخدة مربعة',
                    'مخدة كريسمس',
                    'مخدة كرسي',
                    'مخدة قوس قزح',
                    'مخدة قمر',
                    'مخدة قطرة',
                    'مخدة فيس بوك',
                    'مخدة فرو',
                    'مخدة فالنتاين',
                    'مخدة غيمة',
                    'مخدة صبياني',
                    'مخدة صالون',
                    'مخدة دائرية',
                    'مخدة حيوانات',
                    'مخدة بناتي',
                    'مخدة',
                    'واقي فرشة',
                    'لحاف صيفي',
                    'لحاف صبياني',
                    'لحاف شتوي',
                    'لحاف بناتي',
                    'لحاف + شرشف',
                    'لحاف',
                    'فرشة غيار ب ب',
                    'شرشف صبياني',
                    'شرشف بناتي',
                    'حرام',
                    'بيت لحاف',
                    'كولون',
                    'لفحة نسائي',
                    'لفحة رجالي',
                    'لفاحة صبياني',
                    'لفاحة بناتي',
                    'كفوف',
                    'كاسكيت',
                    'قبعة ولادي',
                    'قبعة نسائي',
                    'قبعة رجالي',
                    'قبعة بناتي',
                    'قبعة + لفاحة ولادي',
                    'بونيه',
                    'فخار',
                    'شمع',
                    'Mug',
                    'دفتر',
                    'notebook',
                    'مقلمة صبياني',
                    'مقلمة بناتي',
                    'محفظة',
                    'خقيبة رياضية',
                    'حقيبة مكياج',
                    'حقيبة رجالي',
                    'حقيبة تاب',
                    'جزدان نسائي',
                    'سكورت',
                    'تنورة شورت',
                    'منشفة رياضي',
                    'منشفة',
                    'ليفة ب ب',
                    'كف حمام',
                    'سجادة بحر',
                    'بشكير وجه',
                    'بشكير مطبخ',
                    'بشكير مسبح',
                    'بشكير رياضي',
                    'بشكير دعسة',
                    'بشكير خصر',
                    'بشكير حمام',
                    'بشكير + ليفة ب ب',
                    'بشكير',
                    'برنص صبياني',
                    'برنص حمام نسائي',
                    'برنص حمام رجالي',
                    'برنص حمام',
                    'برنص بناتي',
                    'فولار نسائي',
                    'خاتم نسائي',
                    'اسوارة',
                    'خاتم ولادي',
                    'بند و بكلة شعر',
                    'معقم',
                    'صابون سائل',
                    'صابون',
                    'shower gel',
                    'Perfume',
                    'Body splash',
                    'body lotion',
                    'حذاء نسائي',
                    'حذاء رجالي',
                    'طقم عرايسي',
                    'طقم داخلي',
                    'سليب',
                    'داخلي نسائي ( بوكسر + بروتيل)',
                    'داخلي',
                    'قميص داخلي',
                    'شيال داخلي',
                    'شيال',
                    'بوكسر',
                    'كرت شيال',
                    "بلوز مع رسومات",
                    "بلوز قصيرة",
                    "بلوز أوفرسايز",
                    "بلوز سادة",
                    "ضيق",
                    "بوي فريند",
                    "عريض"
                ]),
                'en' => $this->faker->randomElement([
                    'kitchen fight', 'mysore', "hanging pyramid shelves",
                    "hanging shelves",
                    "my boy's pocket pendant",
                    'My daughters pocket pendant',
                    'pocket hanging',
                    'walker',
                    'kitchen apron',
                    'shaving apron',
                    "mirror shelf",
                    "neck Pillow",
                    "makeup set",
                    'painting',
                    'lambdir',
                    'Game',
                    'scented sachet',
                    'mask',
                    'chair',
                    'glass base',
                    "dish base",
                    'relationship',
                    "mirror tray",
                    'Box',
                    "wood plate",
                    'cactus',
                    'Ceramic',
                    "my baby basket",
                    "home Basket",
                    'Laundry basket',
                    "my daughters basket",
                    "baby Basket",
                    'Basket',
                    'Wall Clock',
                    'water bag',
                    "beach Bag",
                    'shoe bag',
                    'pocket spoon',
                    'jar',
                    "tableau",
                    'Covereyes',
                    'cover eyes',
                    "women's pencil case",
                    "school pencil case",
                    'Pencil case',
                    "apple",
                    'female girdle',
                    'kemer',
                    'hair bow',
                    'hat',
                    'dome',
                    'Folar',
                    'key hanger',
                    "women's collar",
                    "Children's collar + bracelet",
                    'collar',
                    "sheet",
                    'swara',
                    'freshness chain',
                    "middle leg",
                    'formal long leg',
                    "long leg",
                    'Tie hair',
                    'rubber doxide',
                    'silicon dioxide',
                    'doxide',
                    "brooch",
                    'anklet',
                    'ring',
                    'throat',
                    'hand bag',
                    "women's bag on the side",
                    "women's bag",
                    "mobile bag",
                    'school bag',
                    'laptop bag',
                    "shoulder Bag",
                    'bag on side',
                    "boy Backpack",
                    "men's Backpack",
                    'girls backpack',
                    'back bag',
                    "car bag",
                    "gym Bag",
                    "men's handbag",
                    "men's shoulder bag",
                    "men's backpack",
                    "women's waist bag",
                    "men's waist bag",
                    "waist bag",
                    'girly bag',
                    "ipad bag",
                    'luggage',
                    'hair lock',
                    "men's purses",
                    "two purses",
                    'item',
                    'shin',
                    "accessory",
                    'pod',
                    'shirt',
                    "salopette",
                    'pants',
                    'Swimsuit',
                    'set',
                    'shorts',
                    'dikuna',
                    'pajamas',
                    "polo Blues",
                    "blues",
                    "camisole",
                    "overalls",
                    'dress',
                    "blues With Fizzo",
                    'barbetose',
                    'jacket',
                    'anorak',
                    'Stretch Blues',
                    "fizo",
                    'skirt',
                    'pintcore',
                    "jumper",
                    'sqlist',
                    'gile',
                    'shirt blouse',
                    "shirt collar",
                    'cash may',
                    'cap',
                    'shawl',
                    'rob',
                    'his generation',
                    'bolero',
                    "bustier",
                    "blouse/Camisole",
                    'digging blues',
                    'manto',
                    'drill shirt',
                    'Robe',
                    "leggings",
                    "Rob Dechamber",
                    'pillow face',
                    'birth pillow',
                    "sleeping pillow",
                    "star pillow",
                    "rectangular pillow",
                    "square pillow",
                    "christmas pillow",
                    "chair cushion",
                    "rainbow Pillow",
                    'moon pillow',
                    "drop pillow",
                    'Facebook pillow',
                    "fur Pillow",
                    'valentine pillow',
                    "cloud pillow",
                    "boyish pillow",
                    "salon pillow",
                    'round pillow',
                    "animal pillow",
                    'my daughters pillow',
                    'cushion',
                    "mattress protector",
                    'summer quilt',
                    "boyish quilt",
                    "winter quilt",
                    'my daughters quilt',
                    'quilt + fitted sheet',
                    'quilt',
                    'BB spare mattress',
                    'boyish sheet',
                    'girls sheet',
                    'forbidden',
                    'quilt house',
                    'colon',
                    'female blight',
                    'men blight',
                    'boyish apple',
                    "my daughter's apple",
                    "paws",
                    'casket',
                    "boy hat",
                    "woman's hat",
                    'mens hat',
                    'girly hat',
                    'boy hat + scarf',
                    'bonnet',
                    'pride',
                    'St.. M. P',
                    'Mug',
                    'notebook',
                    "notebook",
                    'boyish pencil case',
                    'Banaty Pencil Case',
                    'wallet',
                    'sports bag',
                    'makeup bag',
                    'mens bag',
                    'tape bag',
                    "women's purse",
                    'scort',
                    'Skirt Shorts',
                    "gym towel",
                    'towel',
                    'lifa bb',
                    "bath palm",
                    "sea rug",
                    'bashkir face',
                    'kitchen towel',
                    'pool towel',
                    "sports towel",
                    'bashkir dasa',
                    'waist towel',
                    "bathrobe",
                    'bashkir + loofah bb',
                    'bashkir',
                    'boyish veil',
                    "women's bathrobe",
                    "men's bathrobe",
                    "bathrobe",
                    'Birnaz Banati',
                    "women's foulard",
                    "women's ring",
                    "bracelet",
                    "birth ring",
                    'Band and a hair clip',
                    'disinfected',
                    'Liquid Soap',
                    'soap',
                    'shower gel',
                    "perfume",
                    'body splash',
                    "body lotion",
                    'women shoes',
                    "men's shoes",
                    "bridal set",
                    'undersuit',
                    'sleep',
                    "women's underwear (boxer + camisole)",
                    'under wear',
                    'underwear',
                    'sack',
                    'boxer',
                    'card sack',
                    "Graphic t-shirt",
                    "crop t-shirt",
                    "Oversized t-shirt",
                    "Basic t-shirt",
                    "Skinny",
                    "Boyfriend",
                    "Wide legs",
                ])
            ],

            'valid' => 1,
        ];
    }
}
